[conquest_aria]
root_dir = ""

[conquest_aria.sql]
uri = ""

[conquest_aria.dicom]
aet = ""
server = ""
port = 0

[conquest_krest]
root_dir = ""
[conquest_krest.sql]
uri = ""

[conquest_krest.dicom]
aet = ""
server = ""
port = 0

[aria]
[aria.sql]
uri = "r"

[aria.dicom]
aet = ""
port = 0
server = ""

[log_db]
uri = ""
file = ""

[krest]
name = ""

[krest.dicom]
aet = ""
server = ""
port = 0